import {
    AvatarFactory,
    Avatar as MantineAvatar,
    MantineColor,
    MantineGradient,
    MantineRadius,
    MantineSize,
} from "@mantine/core";
import { BoxProps } from "props/box";
import { DashBaseProps } from "props/dash";
import { StylesAPIProps } from "props/styles";
import React from "react";

interface Props
    extends BoxProps,
        StylesAPIProps<AvatarFactory["stylesNames"], AvatarFactory["variant"]>,
        DashBaseProps {
    /** Width and height of the avatar, numbers are converted to rem, `'md'` by default */
    size?: MantineSize | (string & {}) | number;
    /** Key of `theme.radius` or any valid CSS value to set border-radius, `'100%'` by default */
    radius?: MantineRadius;
    /** Key of `theme.colors` or any valid CSS color, default value is `theme.primaryColor`  */
    color?: MantineColor | "initials";
    /** Gradient configuration used when `variant="gradient"`, default value is `theme.defaultGradient` */
    gradient?: MantineGradient;
    /** Image url, if the image cannot be loaded or `src={null}`, then placeholder is displayed instead */
    src?: string | null;
    /** Image `alt` attribute, also used as `title` attribute for placeholder */
    alt?: string;
    /** `img` tag attributes */
    imageProps?: object;
    /** Avatar placeholder, displayed when `src={null}` or when the image cannot be loaded */
    children?: React.ReactNode;
    /** Name of the user. When `src` is not set, used to display initials and to generate color when `color="initials"` is set. */
    name?: string;
    /** Determines whether text color with filled variant should depend on `background-color`. If luminosity of the `color` prop is less than `theme.luminosityThreshold`, then `theme.white` will be used for text color, otherwise `theme.black`. Overrides `theme.autoContrast`. */
    autoContrast?: boolean;
    /** An array of colors that can be used for autogenerated initials. By default, all default Mantine colors can be used except gray and dark. */
    allowedInitialsColors?: MantineColor[];
}

/** Avatar */
const Avatar = (props: Props) => {
    const { children, setProps, ...others } = props;

    return <MantineAvatar {...others}>{children}</MantineAvatar>;
};

Avatar.defaultProps = {};

export default Avatar;
