name: Run tests

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  test-react:
    runs-on: ubuntu-latest

    env:
      REACT_VERSION: "19.2.4"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Setup virtual display
        uses: ./.github/actions/setup-virtual-display

      - name: Install package
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install wheel
          uv pip install ".[dev]"
          npm ci
          npm run build
        timeout-minutes: 20

      - name: Install package in editable mode
        run: |
          source .venv/bin/activate
          uv pip install -e .

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --headless